### ISSUE TITLE
Incorrect memory assigned to VM for hotplug_memory tests

### ISSUE THREAD

**Issue by yashkmankad** [avocado-framework/avocado-vt#399]
Hi,

I am running several tests within my CI environment on qemu-kvm , the issue I am filling, is for the test --

**io-github-autotest-qemu.hotplug_memory.after.reboot.hotplug.backend_file.no_policy.one**

Although, I'd like to report the same issue in all the hotplug_memory.after/before/during.reboot tests
with the **exception** of tests that have "unplug.unused_memory"

The error I have in the logfile is --

13:38:35 stacktrace       L0039 ERROR| Reproduced traceback from: /root/avocado-vt/avocado_vt/test.py:400
13:38:35 stacktrace       L0042 ERROR| Traceback (most recent call last):
13:38:35 stacktrace       L0042 ERROR|   File "/root/avocado-vt/avocado_vt/test.py", line 176, in runTest
13:38:35 stacktrace       L0042 ERROR|     self._runTest()
13:38:35 stacktrace       L0042 ERROR|   File "/root/avocado-vt/avocado_vt/test.py", line 318, in _runTest
13:38:35 stacktrace       L0042 ERROR|     run_func(self, params, env)
13:38:35 stacktrace       L0042 ERROR|   File "/root/avocado-vt/virttest/error_context.py", line 135, in new_fn
13:38:35 stacktrace       L0042 ERROR|     return fn(*args, **kwargs)
13:38:35 stacktrace       L0042 ERROR|   File "/usr/share/avocado/data/avocado-vt/test-providers.d/downloads/io-github-autotest-qemu/qemu/tests/hotplug_mem.py", line 109, in run
13:38:35 stacktrace       L0042 ERROR|     hotplug_test.start_test()
13:38:35 stacktrace       L0042 ERROR|   File "/usr/share/avocado/data/avocado-vt/test-providers.d/downloads/io-github-autotest-qemu/qemu/tests/hotplug_mem.py", line 80, in start_test
13:38:35 stacktrace       L0042 ERROR|     func(vm, target_mem)
13:38:35 stacktrace       L0042 ERROR|   File "/root/avocado-vt/virttest/error_context.py", line 135, in new_fn
13:38:35 stacktrace       L0042 ERROR|     return fn(*args, **kwargs)
13:38:35 stacktrace       L0042 ERROR|   File "/root/avocado-vt/virttest/utils_test/qemu.py", line 1661, in hotplug_memory
13:38:35 stacktrace       L0042 ERROR|     self.check_memory(vm)
13:38:35 stacktrace       L0042 ERROR|   File "/root/avocado-vt/virttest/error_context.py", line 135, in new_fn
13:38:35 stacktrace       L0042 ERROR|     return fn(*args, **kwargs)
13:38:35 stacktrace       L0042 ERROR|   File "/root/avocado-vt/virttest/utils_test/qemu.py", line 1761, in check_memory
13:38:35 stacktrace       L0042 ERROR|     raise exceptions.TestFail(msg)
13:38:35 stacktrace       L0042 ERROR| TestFail: Assigned '3072.00MB' memory to 'avocado-vt-vm1'but, '0.97MB' memory detect by OS
13:38:35 stacktrace       L0043 ERROR| 
13:38:35 test             L0535 ERROR| FAIL type_specific.io-github-autotest-qemu.hotplug_memory.after.reboot.hotplug.backend_file.policy_interleave.one -> TestFail: Assigned '3072.00MB' memory to 'avocado-vt-vm1'but, '0.97MB' memory detect by OS

In the test run, we have the parameters 
size_mem = 1G
slots_mem = 4
(You can check the entire log in the attached file)

So, the memory assigned should be '1024.00 MB', but as we can see in the log, it jumps from '1024' to '3072'

It looks like this is happening because of the function "get_vm_mem" 
https://github.com/avocado-framework/avocado-vt/blob/master/virttest/utils_test/qemu.py#L1699
first, it loops over devices and then if "mem" parameter is set, it also adds to global count, which doesn't look right to me. 
1 GB from boot, 1 GB from hotplug and then adds value of "mem", giving us 3 GB (3072.00 MB )  

The second problem is how the memory is being reported/parsed from the guest, the 0.97MB result.
and the hotplug is not being able to reflect in the OS (which may or may not be a separate issue).

I am attaching the entire log file and tagging @xutian , as I believe he authored the section of code being discussed above and also tagging @clebergnu here as he helped me debug these and to keep him updated.

Thanks,
Yash
[avocado_hotplug_error_log.txt](https://github.com/avocado-framework/avocado-vt/files/180462/avocado_hotplug_error_log.txt)

**Comment by xutian** [comment]
@yashkmankad  I will look at this defeat.

**Comment by yashkmankad** [comment]
Thanks @xutian 
You can ping me on RHAT IRC @yash if you need more info.

**Comment by xutian** [comment]
@yashkmankad  view from log, it looks  we boot guest with 2G memory, then hotplug 1G memory to VM, so report assigned 3G memory to VM. but  physical memory report  by OS it looks wrong.

here is another PR fix OS report memory not correct issue, can you apply it and have a try. 
https://github.com/avocado-framework/avocado-vt/pull/366

Thanks,
Xu

**Comment by yashkmankad** [comment]
Hi @xutian ,

The PR seems to workaround that error, but now produces a TypeError() on all the 84 hotplug tests --

12:25:54 stacktrace       L0042 ERROR|   File "/root/avocado-vt/virttest/utils_test/qemu.py", line 1615, in close_sessions
12:25:54 stacktrace       L0042 ERROR|     sessions = reduce(lambda x, y: x + y, self.sessions.values())
12:25:54 stacktrace       L0042 ERROR| TypeError: reduce() of empty sequence with no initial value
12:25:54 stacktrace       L0043 ERROR| 
12:25:54 test             L0518 ERROR| Traceback (most recent call last):
12:25:54 test             L0518 ERROR|   File "/root/avocado-vt/avocado_vt/test.py", line 414, in _run_avocado
12:25:54 test             L0518 ERROR| TypeError: reduce() of empty sequence with no initial value
12:25:54 test             L0535 ERROR| ERROR type_specific.io-github-autotest-qemu.hotplug_memory.after.reboot.hotplug.backend_file.no_policy.one -> TypeError: reduce() of empty sequence with no initial value

Attaching the full log.
[avocado_hotplug_error_log_#2.txt](https://github.com/avocado-framework/avocado-vt/files/182877/avocado_hotplug_error_log_.2.txt)

**Comment by yashkmankad** [comment]
Hello @xutian ,

Also, on the comment about assigned memory, in the log file, the mem parameter is 1G 

13:37:10 test             L0209 DEBUG|     **mem = 1024**

and even in the qemu-kvm command line (which is being sent) , the parameter passed to qemu-kvm command reflects 1 G 

13:37:12 qemu_vm          L2572 INFO | Running qemu command (reformatted):
MALLOC_PERTURB_=1  /usr/libexec/qemu-kvm \
    -S  \
    -name 'avocado-vt-vm1' \
    -machine pc  \
    -nodefaults  \
    -vga std  \
    ......
    -netdev user,id=idWduJov,hostfwd=tcp::5000-:22 \
   ** -m 1024**,slots=4,maxmem=32G \
    ......
    -enable-kvm

and then hotplug is 1G.

13:37:14 error_context    L0079 INFO | Context: (run) --> Hotplug memory 'mem-plug' to VM
13:37:14 qemu_monitor     L0286 DEBUG| (monitor qmp1) Sending command 'object-add' 
13:37:14 qemu_monitor     L1454 DEBUG| Send command: {'execute': 'object-add', 'arguments': {'id': 'mem-plug', 'qom-type': 'memory-backend-file', 'props': {'policy': 'interleave', 'mem-path': '/mnt/kvm_hugepage', 'host-nodes': [0],** 'size': 1073741824**}}, 'id': 'bHMtEmro'}

So assigned memory should be 2G and not 3G ?

Feel free to correct me if I am interpreting the logs incorrectly. 

Thanks,
Yash

**Comment by xutian** [comment]
@yashkmankad  really has bug when count memory assigned to VM, now it fixed in PR https://github.com/avocado-framework/avocado-vt/pull/366. would you like to have a try with latest code.

Thanks,
Xu

**Comment by yashkmankad** [comment]
Hi @xutian,

Thanks for the PR.
The PR seemed to fix the TypeError, but the tests are still failing with 3 different errors now.
And one of those is the original VM memory error --

 21:25:35 stacktrace       L0036 ERROR| 
21:25:35 stacktrace       L0039 ERROR| Reproduced traceback from: /root/avocado-vt/avocado_vt/test.py:400
21:25:35 stacktrace       L0042 ERROR| Traceback (most recent call last):
21:25:35 stacktrace       L0042 ERROR|   File "/root/avocado-vt/avocado_vt/test.py", line 176, in runTest
21:25:35 stacktrace       L0042 ERROR|     self._runTest()
21:25:35 stacktrace       L0042 ERROR|   File "/root/avocado-vt/avocado_vt/test.py", line 318, in _runTest
21:25:35 stacktrace       L0042 ERROR|     run_func(self, params, env)
21:25:35 stacktrace       L0042 ERROR|   File "/root/avocado-vt/virttest/error_context.py", line 135, in new_fn
21:25:35 stacktrace       L0042 ERROR|     return fn(*args, **kwargs)
21:25:35 stacktrace       L0042 ERROR|   File "/usr/share/avocado/data/avocado-vt/test-providers.d/downloads/io-github-autotest-qemu/qemu/tests/hotplug_mem.py", line 109, in run
21:25:35 stacktrace       L0042 ERROR|     hotplug_test.start_test()
21:25:35 stacktrace       L0042 ERROR|   File "/usr/share/avocado/data/avocado-vt/test-providers.d/downloads/io-github-autotest-qemu/qemu/tests/hotplug_mem.py", line 80, in start_test
21:25:35 stacktrace       L0042 ERROR|     func(vm, target_mem)
21:25:35 stacktrace       L0042 ERROR|   File "/root/avocado-vt/virttest/error_context.py", line 135, in new_fn
21:25:35 stacktrace       L0042 ERROR|     return fn(*args, **kwargs)
21:25:35 stacktrace       L0042 ERROR|   File "/root/avocado-vt/virttest/utils_test/qemu.py", line 1694, in hotplug_memory
21:25:35 stacktrace       L0042 ERROR|     self.check_memory(vm)
21:25:35 stacktrace       L0042 ERROR|   File "/root/avocado-vt/virttest/error_context.py", line 135, in new_fn
21:25:35 stacktrace       L0042 ERROR|     return fn(*args, **kwargs)
21:25:35 stacktrace       L0042 ERROR|   File "/root/avocado-vt/virttest/utils_test/qemu.py", line 1778, in check_memory
21:25:35 stacktrace       L0042 ERROR|     raise exceptions.TestFail(msg)
21:25:35 stacktrace       L0042 ERROR| TestFail: Assigned '3072 MB' memory to 'avocado-vt-vm1'but, '993 MB' memory detect by OS
21:25:35 stacktrace       L0043 ERROR| 
21:25:35 test             L0535 **ERROR| FAIL type_specific.io-github-autotest-qemu.hotplug_memory.after.reboot.hotplug.backend_file.policy_bind.one -> TestFail: Assigned '3072 MB' memory to 'avocado-vt-vm1'but, '993 MB' memory detect by OS**

Please find attached the logs --
[avocado_hotplug_error_log_#3.txt](https://github.com/avocado-framework/avocado-vt/files/198895/avocado_hotplug_error_log_.3.txt)
[avocado_hotplug_error_log_#4.txt](https://github.com/avocado-framework/avocado-vt/files/198894/avocado_hotplug_error_log_.4.txt)
[avocado_hotplug_error_log_#5.txt](https://github.com/avocado-framework/avocado-vt/files/198896/avocado_hotplug_error_log_.5.txt)

Since the original issue has been filed for the test **io-github-autotest-qemu.hotplug_memory.after.reboot.hotplug.backend_file.no_policy.one** , the log for that test is error_log_#3.txt  

error_log_#4 and #5 are just for reference as these errors started appearing after the PR#366 was applied.

Thanks,
Yash

**Comment by xutian** [comment]
@yashkmankad  which channel I can find you? I have join channel @kvm @kvm-qe and @eng-china.

**Comment by xutian** [comment]
@yashkmankad  do you still have problem on memory hotplug related testcase, if no I will close this issue.

thanks,
Xu

**Comment by yashkmankad** [comment]
@xutian I did not get time over the weekend to check all the tests. I will do so tomorrow and if I don't see an issue (which I am hoping not to), I will close it myself.

Thanks for all the help!
Yash

**Comment by xutian** [comment]
Thanks your quick response, In my mind, unplug memory still have bug in rhel guest kernel,  so most of unplug test maybe failed.
FYI.

thanks,
Xu

**Comment by yashkmankad** [comment]
@xutian -- doesn't seem like systemd issue.
I upgraded JeOS image from 21 to 23 based on fix #472 

[root@atest-guest ~]# cat /etc/*-release
Fedora release 23 (Twenty Three)

and systemd is version 2.22
Hotplug memory was fixed in 2.19 according to Bugzilla

[root@atest-guest ~]# systemctl --version
systemd 222
+PAM +AUDIT +SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ -LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN

yet...

[root@atest-guest ~]# cd /sys/devices/system/memory
[root@atest-guest memory]# find ./ -name 'state' -exec cat {} \;
online
online
online
online
online
online
online
online
offline
offline
offline
offline
offline
offline
offline
offline
offline
offline
offline
offline
offline
offline
offline
offline

**Comment by yashkmankad** [comment]
@xutian 

However, the test passes!

[root@virtlab506 ~]# avocado run io-github-autotest-qemu.hotplug_memory.after.guest_reboot.hotplug.backend_file.no_policy.one
JOB ID     : 55965b9a1a9bb6d4aa09ca625dc8371c7f6fe06f
JOB LOG    : /home/jenkins/avocado/job-results/job-2016-04-27T14.41-55965b9/job.log
TESTS      : 1
 (1/1) type_specific.io-github-autotest-qemu.hotplug_memory.after.guest_reboot.hotplug.backend_file.no_policy.one: PASS (136.35 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0
JOB HTML   : /home/jenkins/avocado/job-results/job-2016-04-27T14.41-55965b9/html/results.html
TIME       : 136.35 s


The weird thing is, when I take out the sleep command that we added to debug the issue,
in file 
/usr/share/avocado/data/avocado-vt/test-providers.d/downloads/io-github-autotest-qemu/qemu/tests/hotplug_mem.py", line 80, in start_test

    def start_test(self):
        try:
            target_mem = self.params["target_mem"]
            operation = self.params["operation"]
            vm = self.env.get_vm(self.params["main_vm"])
            if self.params.get("stage") == "before":
                self.run_sub_test()
            # If unplug memory not exits and test in instrcit then hotplug it
            if operation == "unplug":
                devs = self.get_mem_by_name(vm, target_mem)
                if not devs and self.params.get("strict") != "yes":
                    self.hotplug_memory(vm, target_mem)
            func_name = "%s_memory" % operation
            func = getattr(self, func_name)
            if self.params.get("stage") == "during":
                sub_test = self.run_background_test()
            func(vm, target_mem)
            if self.params.get("stage") == "during":
                test_timeout = float(self.params.get("sub_test_timeout", 3600))
                sub_test.join(timeout=test_timeout)
            if self.params.get("stage") == "after":
                self.run_sub_test()
            post_vm = self.env.get_vm(self.params["main_vm"])
            self.restore_memory(vm, post_vm)
#        except Exception:
#           import time; time.sleep(100)
        finally:
            self.close_sessions()

the test fails... 

[root@virtlab506 ~]# avocado run io-github-autotest-qemu.hotplug_memory.after.guest_reboot.hotplug.backend_file.no_policy.one
JOB ID     : 1fb9ca3027b55078c944d4c440232253b4048371
JOB LOG    : /home/jenkins/avocado/job-results/job-2016-04-27T14.47-1fb9ca3/job.log
TESTS      : 1
 (1/1) type_specific.io-github-autotest-qemu.hotplug_memory.after.guest_reboot.hotplug.backend_file.no_policy.one: FAIL (28.16 s)
RESULTS    : PASS 0 | ERROR 0 | FAIL 1 | SKIP 0 | WARN 0 | INTERRUPT 0
JOB HTML   : /home/jenkins/avocado/job-results/job-2016-04-27T14.47-1fb9ca3/html/results.html
TIME       : 28.16 s

Although I believe this is due to adding the "except Exception" line.

Thoughts?

Thanks,
Yash

**Comment by xutian** [comment]
@yashkmankad  thanks your comments.  I'm not sure systemd in fedora23 include fix about online hotpluged memory by default.  We have a test with latest rhel 7 guest it works fine, you can see job link in bug 1285311.
In order to avoid impact from systemd , I send a new patch https://github.com/avocado-framework/avocado-vt/pull/443, maybe you can have a try.
And in our internal test, we found memory report by windows guest OS is incorrect (Linux guest works fine) and I have another patch https://github.com/avocado-framework/avocado-vt/pull/471.

If you have time, can you fetch latest avocado-vt source code and apply patch 443 and 471 to have try. 

thanks very much.

**Comment by yashkmankad** [comment]
Patch #471 fixes the issue.
Thanks @xutian !
